### ISSUE TITLE
Requirements missing '='

### ISSUE THREAD

**Issue by certanet** [wifiwizardofoz/ciscoPWDhasher#2]
Error when installing requirements...

https://github.com/wifiwizardofoz/ciscoPWDhasher/blob/c0dacc1bfaecb49a9012cc4098129238bf5a3ba8/requirements.txt#L3

Line should be:
`passlib==1.7.4`

Thanks for the tool 👍

**Comment by BrettVerney** [comment]
> Line should be:
> `passlib==1.7.4`

Fixed. Thanks for pointing this out!
