### ISSUE TITLE
Unable to integrate into larger projects

### ISSUE THREAD

**Issue by superadm1n** [wifiwizardofoz/ciscoPWDhasher#5]
I think the code in this would be better if it was restructured to a package so one could install it via pip and use the hashing functions in a larger project vs having to copy the code out. This would open up the ability to publish this package on pypi and do a 'pip install ciscoPWDhasher' and import the hashing function you need to use. This would also not change the name or functionality of the 'ciscopwdhasher.py' script, only the structure of the code.

**Comment by BrettVerney** [comment]
Hey Kyle,

I've just finished a project for 12 months or so which sucked up all of my time. I've been meaning to get back to you about this. I also needed time to go through it as your Python skills are obviously well beyond mine. I've merged the changes, and also made you a collaborator! I hoping to finally implement Type 10 and fix some of the issues re: Type 9 on some of the latest IOS-XE versions.
